[versions]
kotlin = "1.5.31"
serialization = "1.3.0"
ktor = "1.6.2"
koin = "3.1.2"
kmmLibrary = "1.4.3"
moko-mvvm = "0.11.0"
versionChecker = "0.39.0"
sqldelight = "1.5.1"

# android
appCompat = "1.3.1"
activity = "1.3.1"
annotation = "1.2.0-alpha01"
material = "1.4.0"
coroutines = "1.5.2"
fragment = "1.3.6"
constraintLayout = "2.0.4"
lifecycle = "2.3.1"
cardView = "1.0.0"
recyclerView = "1.2.1"
dagger = "2.38.1"
navigation = "2.3.5"
paging = "3.0.1"
billing = "4.0.0"
publisher = "v3-rev20210728-1.32.1"
auth = "1.0.0"
firebaseFirestore = "23.0.3"
playCore = "1.10.1"
keyboard = "3.0.0-RC3"
gson = "2.8.8"
worker = "2.6.0"
room = "2.3.0"
rxjava2 = "2.2.20"
coil = "1.3.2"
typedDataStore = "1.0.0"
location = "18.0.0"
bouncyCastle = "1.65"
phoneValidator = "8.12.26"
zip4j = "2.9.0"

firebaseMessaging = "22.0.0"

merseyLib = "1.6.1"
filemanager = "1.0.7"
firestoreCoroutines = "1.0.3"

time = "1.0.5"

# multiplatform
multiplatform-coroutines = "1.5.2-native-mt"
moko-resources = "0.15.1"
settings = "0.8"

[libraries]
serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref="serialization" }
merseyLib-time = { module = "io.github.merseyside:time", version.ref = "time" }

android-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
android-appCompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
android-activityKtx = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
android-material = { module = "com.google.android.material:material", version.ref = "material" }
android-fragment = { module = "androidx.fragment:fragment", version.ref = "fragment" }
android-recyclerView = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerView" }
android-constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
android-lifecycleViewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
android-lifecycleViewModelSavedState = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }
android-lifecycleLiveDataKtx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
android-cardView = { module = "androidx.cardview:cardview", version.ref = "cardView" }
android-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
android-rxjava2 = { module = "io.reactivex.rxjava2:rxjava", version.ref = "rxjava2" }
android-paging = { module = "androidx.paging:paging-runtime", version.ref = "paging" }
android-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
android-playCore = { module = "com.google.android.play:core", version.ref = "playCore" }
android-billing = { module = "com.android.billingclient:billing-ktx", version.ref = "billing" }
android-publisher = { module = "com.google.apis:google-api-services-androidpublisher", version.ref = "publisher" }
android-firebaseFirestore = { module = "com.google.firebase:firebase-firestore-ktx", version.ref = "firebaseFirestore" }
android-oauth2 = { module = "com.google.auth:google-auth-library-oauth2-http", version.ref = "auth" }
android-room = { module = "androidx.room:room-runtime", version.ref = "room" }
android-roomCompiler = { module = "androidx.room:room-compiler", version.ref = "room" }
android-roomKtx = { module = "androidx.room:room-ktx", version.ref = "room" }
android-dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
android-daggerCompiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
android-navigation = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
android-navigationUi = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
android-keyboard = { module = "net.yslibrary.keyboardvisibilityevent:keyboardvisibilityevent", version.ref = "keyboard" }
android-worker = { module = "androidx.work:work-runtime-ktx", version.ref = "worker" }
android-gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
android-coil = { module = "io.coil-kt:coil", version.ref = "coil" }
android-typedDataStore = { module = "androidx.datastore:datastore", version.ref = "typedDataStore" }
android-location = { module = "com.google.android.gms:play-services-location", version.ref = "location" }
android-koin = { module = "io.insert-koin:koin-android", version.ref = "koin" }
android-sqldelight = { module = "com.squareup.sqldelight:android-driver", version.ref = "sqldelight" }
android-bouncyCastle = { module = "org.bouncycastle:bcpkix-jdk15on", version.ref = "bouncyCastle" }
android-phoneValidator = { module = "com.googlecode.libphonenumber:libphonenumber", version.ref = "phoneValidator" }
android-zip4j = { module = "net.lingala.zip4j:zip4j", version.ref = "zip4j" }

android-ktor = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
android-ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }

android-moko-mvvmDatabinding = { module = "dev.icerock.moko:mvvm-databinding", version.ref = "moko-mvvm" }
android-moko-mvvmViewBinding = { module = "dev.icerock.moko:mvvm-viewbinding", version.ref = "moko-mvvm" }
android-moko-mvvmLiveDataMaterial = { module = "dev.icerock.moko:mvvm-livedata-material", version.ref = "moko-mvvm" }

android-firebase-messaging = { module = "com.google.firebase:firebase-messaging-ktx", version.ref="firebaseMessaging" }

# Mersey libs
android-merseyLib-archy = { module = "com.github.Merseyside.mersey-android-library:archy", version.ref="merseyLib" }
android-merseyLib-adapters = { module = "com.github.Merseyside.mersey-android-library:adapters", version.ref="merseyLib"}
android-merseyLib-animators = { module = "com.github.Merseyside.mersey-android-library:animators", version.ref="merseyLib" }
android-merseyLib-utils = { module = "com.github.Merseyside.mersey-android-library:utils", version.ref="merseyLib" }
android-merseyLib-filemanager = { module = "com.github.Merseyside:android-filemanager", version.ref="filemanager" }
android-merseyLib-firestoreCoroutines = { module = "com.github.Merseyside:firestore-coroutines", version.ref="firestoreCoroutines" }

android-merseyLib-archyAndroid = { module = "io.github.merseyside:archy-android", version.ref = "kmmLibrary" }

# Multiplatform
multiplatform-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref= "multiplatform-coroutines" }
multiplatform-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref="serialization" }
multiplatform-koin = { module = "io.insert-koin:koin-core", version.ref = "koin" }
multiplatform-sqldelight = { module = "com.squareup.sqldelight:runtime", version.ref = "sqldelight" }
multiplatform-sqldelight-coroutines = { module = "com.squareup.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "settings"}

multiplatform-ktor = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
multiplatform-ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
multiplatform-ktor-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }

multiplatform-moko-mvvm = { module = "dev.icerock.moko:mvvm-core", version.ref = "moko-mvvm" }
multiplatform-moko-mvvm-livedata = { module = "dev.icerock.moko:mvvm-livedata", version.ref = "moko-mvvm" }
multiplatform-moko-resources = { module = "dev.icerock.moko:resources", version.ref = "moko-resources" }

# Mersey libs
multiplatform-merseyLib-archyCore = { module = "io.github.merseyside:archy-core", version.ref = "kmmLibrary" }
multiplatform-merseyLib-utilsCore = { module = "io.github.merseyside:utils-core", version.ref = "kmmLibrary" }

[bundles]
android-lifecycle = ["android-lifecycleViewModel", "android-lifecycleViewModelSavedState", "android-lifecycleLiveDataKtx"]
android-navigation = ["android-navigation", "android-navigationUi"]
android-room = ["android-room", "android-roomKtx"]
android-merseyLibs = ["android-merseyLib-archy", "android-merseyLib-adapters", "android-merseyLib-animators", "android-merseyLib-utils"]
android-moko-mvvm = ["android-moko-mvvmDatabinding", "android-moko-mvvmViewBinding", "android-moko-mvvmLiveDataMaterial"]
android-ktor = ["android-ktor", "android-ktor-okhttp"]

multiplatform-moko-mvvm = ["multiplatform-moko-mvvm", "multiplatform-moko-mvvm-livedata"]
multiplatform-ktor = ["multiplatform-ktor", "multiplatform-ktor-logging", "multiplatform-ktor-auth"]
multiplatform-merseyLibs = ["multiplatform-merseyLib-archyCore", "multiplatform-merseyLib-utilsCore"]

[plugins]
versionChecker = { id = "com.github.ben-manes.versions", version.ref = "versionChecker"}